import type { ELAStandard, GradeLevel, StandardStrand } from "./types.js";

const ALL_STANDARDS: ELAStandard[] = [
  // ─── GRADE 3 ── Reading Literature ───────────────────────────────────────────
  {
    code: "RL.3.1",
    strand: "RL",
    grade: 3,
    number: "1",
    text: "Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RL.3.2",
    strand: "RL",
    grade: 3,
    number: "2",
    text: "Recount stories, including fables, folktales, and myths from diverse cultures; determine the central message, lesson, or moral and explain how it is conveyed through key details in the text.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RL.3.3",
    strand: "RL",
    grade: 3,
    number: "3",
    text: "Describe characters in a story (e.g., their traits, motivations, or feelings) and explain how their actions contribute to the sequence of events.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "character_analysis"],
  },
  {
    code: "RL.3.4",
    strand: "RL",
    grade: 3,
    number: "4",
    text: "Determine the meaning of words and phrases as they are used in a text, distinguishing literal from nonliteral language.",
    useFor: ["vocabulary"],
  },
  {
    code: "RL.3.5",
    strand: "RL",
    grade: 3,
    number: "5",
    text: "Refer to parts of stories, dramas, and poems when writing or speaking about a text, using terms such as chapter, scene, and stanza; describe how each successive part builds on earlier sections.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.3.6",
    strand: "RL",
    grade: 3,
    number: "6",
    text: "Distinguish their own point of view from that of the narrator or those of the characters.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.3.9",
    strand: "RL",
    grade: 3,
    number: "9",
    text: "Compare and contrast the themes, settings, and plots of stories written by the same author about the same or similar characters (e.g., in books from a series).",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 3 ── Reading Informational ────────────────────────────────────────
  {
    code: "RI.3.1",
    strand: "RI",
    grade: 3,
    number: "1",
    text: "Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RI.3.2",
    strand: "RI",
    grade: 3,
    number: "2",
    text: "Determine the main idea of a text; recount the key details and explain how they support the main idea.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RI.3.3",
    strand: "RI",
    grade: 3,
    number: "3",
    text: "Describe the relationship between a series of historical events, scientific ideas or concepts, or steps in technical procedures in a text, using language that pertains to time, sequence, and cause/effect.",
    useFor: ["think_about_the_story", "reading_between_the_lines"],
  },
  {
    code: "RI.3.4",
    strand: "RI",
    grade: 3,
    number: "4",
    text: "Determine the meaning of general academic and domain-specific words and phrases in a text relevant to a grade 3 topic or subject area.",
    useFor: ["vocabulary"],
  },
  {
    code: "RI.3.6",
    strand: "RI",
    grade: 3,
    number: "6",
    text: "Distinguish their own point of view from that of the author of a text.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RI.3.8",
    strand: "RI",
    grade: 3,
    number: "8",
    text: "Describe the logical connection between particular sentences and paragraphs in a text (e.g., comparison, cause/effect, first/second/third in a sequence).",
    useFor: ["reading_between_the_lines", "dig_deeper"],
  },
  {
    code: "RI.3.9",
    strand: "RI",
    grade: 3,
    number: "9",
    text: "Compare and contrast the most important points and key details presented in two texts on the same topic.",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 3 ── Writing ───────────────────────────────────────────────────────
  {
    code: "W.3.1",
    strand: "W",
    grade: 3,
    number: "1",
    text: "Write opinion pieces on topics or texts, supporting a point of view with reasons.",
    useFor: ["creative_response"],
  },
  {
    code: "W.3.2",
    strand: "W",
    grade: 3,
    number: "2",
    text: "Write informative/explanatory texts to examine a topic and convey ideas and information clearly.",
    useFor: ["creative_response"],
  },
  {
    code: "W.3.3",
    strand: "W",
    grade: 3,
    number: "3",
    text: "Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences.",
    useFor: ["creative_response"],
  },
  {
    code: "W.3.4",
    strand: "W",
    grade: 3,
    number: "4",
    text: "With guidance and support from adults, produce writing in which the development and organization are appropriate to task and purpose.",
    useFor: ["creative_response"],
  },
  {
    code: "W.3.5",
    strand: "W",
    grade: 3,
    number: "5",
    text: "With guidance and support from peers and adults, develop and strengthen writing as needed by planning, revising, and editing.",
    useFor: ["creative_response"],
  },
  {
    code: "W.3.8",
    strand: "W",
    grade: 3,
    number: "8",
    text: "Recall information from experiences or gather information from print and digital sources; take brief notes on sources and sort evidence into provided categories.",
    useFor: ["evidence_from_the_story"],
  },
  {
    code: "W.3.10",
    strand: "W",
    grade: 3,
    number: "10",
    text: "Write routinely over extended time frames (time for research, reflection, and revision) and shorter time frames (a single sitting or a day or two) for a range of discipline-specific tasks, purposes, and audiences.",
    useFor: ["creative_response"],
  },

  // ─── GRADE 4 ── Reading Literature ───────────────────────────────────────────
  {
    code: "RL.4.1",
    strand: "RL",
    grade: 4,
    number: "1",
    text: "Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RL.4.2",
    strand: "RL",
    grade: 4,
    number: "2",
    text: "Determine a theme of a story, drama, or poem from details in the text; summarize the text.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RL.4.3",
    strand: "RL",
    grade: 4,
    number: "3",
    text: "Describe in depth a character, setting, or event in a story or drama, drawing on specific details in the text (e.g., a character's thoughts, words, or actions).",
    useFor: ["think_about_the_story", "reading_between_the_lines", "character_analysis"],
  },
  {
    code: "RL.4.4",
    strand: "RL",
    grade: 4,
    number: "4",
    text: "Determine the meaning of words and phrases as they are used in a text, including those that allude to significant characters found in mythology (e.g., Herculean).",
    useFor: ["vocabulary"],
  },
  {
    code: "RL.4.5",
    strand: "RL",
    grade: 4,
    number: "5",
    text: "Explain major differences between poems, drama, and prose, and refer to the structural elements of poems (e.g., verse, rhythm, meter) and drama (e.g., casts of characters, settings, descriptions, dialogue, stage directions) when writing or speaking about a text.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.4.6",
    strand: "RL",
    grade: 4,
    number: "6",
    text: "Compare and contrast the point of view from which different stories are narrated, including the difference between first- and third-person narrations.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.4.9",
    strand: "RL",
    grade: 4,
    number: "9",
    text: "Compare and contrast the treatment of similar themes and topics (e.g., opposition of good and evil) and patterns of events (e.g., the quest) in stories, myths, and traditional literature from different cultures.",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 4 ── Reading Informational ────────────────────────────────────────
  {
    code: "RI.4.1",
    strand: "RI",
    grade: 4,
    number: "1",
    text: "Refer to details and examples in a text when explaining what the text says explicitly and when drawing inferences from the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RI.4.2",
    strand: "RI",
    grade: 4,
    number: "2",
    text: "Determine the main idea of a text and explain how it is supported by key details; summarize the text.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RI.4.3",
    strand: "RI",
    grade: 4,
    number: "3",
    text: "Explain events, procedures, ideas, or concepts in a historical, scientific, or technical text, including what happened and why, based on specific information in the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines"],
  },
  {
    code: "RI.4.4",
    strand: "RI",
    grade: 4,
    number: "4",
    text: "Determine the meaning of general academic and domain-specific words or phrases in a text relevant to a grade 4 topic or subject area.",
    useFor: ["vocabulary"],
  },
  {
    code: "RI.4.6",
    strand: "RI",
    grade: 4,
    number: "6",
    text: "Compare and contrast a firsthand and secondhand account of the same event or topic; describe the differences in focus and the information provided.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RI.4.8",
    strand: "RI",
    grade: 4,
    number: "8",
    text: "Explain how an author uses reasons and evidence to support particular points in a text.",
    useFor: ["reading_between_the_lines", "dig_deeper"],
  },
  {
    code: "RI.4.9",
    strand: "RI",
    grade: 4,
    number: "9",
    text: "Integrate information from two texts on the same topic in order to write or speak about the subject knowledgeably.",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 4 ── Writing ───────────────────────────────────────────────────────
  {
    code: "W.4.1",
    strand: "W",
    grade: 4,
    number: "1",
    text: "Write opinion pieces on topics or texts, supporting a point of view with reasons and information.",
    useFor: ["creative_response"],
  },
  {
    code: "W.4.2",
    strand: "W",
    grade: 4,
    number: "2",
    text: "Write informative/explanatory texts to examine a topic and convey ideas and information clearly.",
    useFor: ["creative_response"],
  },
  {
    code: "W.4.3",
    strand: "W",
    grade: 4,
    number: "3",
    text: "Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences.",
    useFor: ["creative_response"],
  },
  {
    code: "W.4.4",
    strand: "W",
    grade: 4,
    number: "4",
    text: "Produce clear and coherent writing in which the development and organization are appropriate to task, purpose, and audience.",
    useFor: ["creative_response"],
  },
  {
    code: "W.4.5",
    strand: "W",
    grade: 4,
    number: "5",
    text: "With guidance and support from peers and adults, develop and strengthen writing as needed by planning, revising, and editing.",
    useFor: ["creative_response"],
  },
  {
    code: "W.4.9",
    strand: "W",
    grade: 4,
    number: "9",
    text: "Draw evidence from literary or informational texts to support analysis, reflection, and research.",
    useFor: ["evidence_from_the_story"],
  },
  {
    code: "W.4.9a",
    strand: "W",
    grade: 4,
    number: "9",
    subNumber: "a",
    text: "Apply grade 4 Reading standards to literature (e.g., 'Describe in depth a character, setting, or event in a story or drama, drawing on specific details in the text').",
    useFor: ["evidence_from_the_story"],
  },
  {
    code: "W.4.10",
    strand: "W",
    grade: 4,
    number: "10",
    text: "Write routinely over extended time frames (time for research, reflection, and revision) and shorter time frames (a single sitting or a day or two) for a range of discipline-specific tasks, purposes, and audiences.",
    useFor: ["creative_response"],
  },

  // ─── GRADE 5 ── Reading Literature ───────────────────────────────────────────
  {
    code: "RL.5.1",
    strand: "RL",
    grade: 5,
    number: "1",
    text: "Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RL.5.2",
    strand: "RL",
    grade: 5,
    number: "2",
    text: "Determine a theme of a story, drama, or poem from details in the text, including how characters in a story or drama respond to challenges or how the speaker in a poem reflects upon a topic; summarize the text.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RL.5.3",
    strand: "RL",
    grade: 5,
    number: "3",
    text: "Compare and contrast two or more characters, settings, or events in a story or drama, drawing on specific details in the text (e.g., how characters interact).",
    useFor: ["think_about_the_story", "reading_between_the_lines", "character_analysis"],
  },
  {
    code: "RL.5.4",
    strand: "RL",
    grade: 5,
    number: "4",
    text: "Determine the meaning of words and phrases as they are used in a text, including figurative language such as metaphors and similes.",
    useFor: ["vocabulary"],
  },
  {
    code: "RL.5.5",
    strand: "RL",
    grade: 5,
    number: "5",
    text: "Explain how a series of chapters, scenes, or stanzas fits together to provide the overall structure of a particular story, drama, or poem.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.5.6",
    strand: "RL",
    grade: 5,
    number: "6",
    text: "Describe how a narrator's or speaker's point of view influences how events are described.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.5.9",
    strand: "RL",
    grade: 5,
    number: "9",
    text: "Compare and contrast stories in the same genre (e.g., mysteries and adventure stories) on their approaches to similar themes and topics.",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 5 ── Reading Informational ────────────────────────────────────────
  {
    code: "RI.5.1",
    strand: "RI",
    grade: 5,
    number: "1",
    text: "Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RI.5.2",
    strand: "RI",
    grade: 5,
    number: "2",
    text: "Determine two or more main ideas of a text and explain how they are supported by key details; summarize the text.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RI.5.3",
    strand: "RI",
    grade: 5,
    number: "3",
    text: "Explain the relationships or interactions between two or more individuals, events, ideas, or concepts in a text based on specific information in the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines"],
  },
  {
    code: "RI.5.4",
    strand: "RI",
    grade: 5,
    number: "4",
    text: "Determine the meaning of general academic and domain-specific words and phrases in a text relevant to a grade 5 topic or subject area.",
    useFor: ["vocabulary"],
  },
  {
    code: "RI.5.6",
    strand: "RI",
    grade: 5,
    number: "6",
    text: "Analyze multiple accounts of the same event or topic, noting important similarities and differences in the point of view they represent.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RI.5.8",
    strand: "RI",
    grade: 5,
    number: "8",
    text: "Explain how an author uses reasons and evidence to support particular points in a text, identifying which reasons and evidence support which point(s).",
    useFor: ["reading_between_the_lines", "dig_deeper"],
  },
  {
    code: "RI.5.9",
    strand: "RI",
    grade: 5,
    number: "9",
    text: "Integrate information from several texts on the same topic in order to write or speak about the subject knowledgeably.",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 5 ── Writing ───────────────────────────────────────────────────────
  {
    code: "W.5.1",
    strand: "W",
    grade: 5,
    number: "1",
    text: "Write opinion pieces on topics or texts, supporting a point of view with reasons and information.",
    useFor: ["creative_response"],
  },
  {
    code: "W.5.1a",
    strand: "W",
    grade: 5,
    number: "1",
    subNumber: "a",
    text: "Introduce a topic or text clearly, state an opinion, and create an organizational structure in which ideas are logically grouped to support the writer's purpose.",
    useFor: ["creative_response"],
  },
  {
    code: "W.5.1b",
    strand: "W",
    grade: 5,
    number: "1",
    subNumber: "b",
    text: "Provide logically ordered reasons that are supported by facts and details.",
    useFor: ["creative_response"],
  },
  {
    code: "W.5.1d",
    strand: "W",
    grade: 5,
    number: "1",
    subNumber: "d",
    text: "Provide a concluding statement or section related to the opinion presented.",
    useFor: ["creative_response"],
  },
  {
    code: "W.5.2",
    strand: "W",
    grade: 5,
    number: "2",
    text: "Write informative/explanatory texts to examine a topic and convey ideas and information clearly.",
    useFor: ["creative_response"],
  },
  {
    code: "W.5.3",
    strand: "W",
    grade: 5,
    number: "3",
    text: "Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences.",
    useFor: ["creative_response"],
  },
  {
    code: "W.5.4",
    strand: "W",
    grade: 5,
    number: "4",
    text: "Produce clear and coherent writing in which the development and organization are appropriate to task, purpose, and audience.",
    useFor: ["creative_response"],
  },
  {
    code: "W.5.5",
    strand: "W",
    grade: 5,
    number: "5",
    text: "With guidance and support from peers and adults, develop and strengthen writing as needed by planning, drafting, revising, editing, rewriting, or trying a new approach.",
    useFor: ["creative_response"],
  },
  {
    code: "W.5.9",
    strand: "W",
    grade: 5,
    number: "9",
    text: "Draw evidence from literary or informational texts to support analysis, reflection, and research.",
    useFor: ["evidence_from_the_story"],
  },
  {
    code: "W.5.9a",
    strand: "W",
    grade: 5,
    number: "9",
    subNumber: "a",
    text: "Apply grade 5 Reading standards to literature (e.g., 'Describe how a narrator's or speaker's point of view influences how events are described').",
    useFor: ["evidence_from_the_story"],
  },
  {
    code: "W.5.10",
    strand: "W",
    grade: 5,
    number: "10",
    text: "Write routinely over extended time frames (time for research, reflection, and revision) and shorter time frames (a single sitting or a day or two) for a range of discipline-specific tasks, purposes, and audiences.",
    useFor: ["creative_response"],
  },

  // ─── GRADE 6 ── Reading Literature ───────────────────────────────────────────
  {
    code: "RL.6.1",
    strand: "RL",
    grade: 6,
    number: "1",
    text: "Cite textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RL.6.2",
    strand: "RL",
    grade: 6,
    number: "2",
    text: "Determine a theme or central idea of a text and how it is conveyed through particular details; provide a summary of the text distinct from personal opinions or judgments.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RL.6.3",
    strand: "RL",
    grade: 6,
    number: "3",
    text: "Describe how a particular story's or drama's plot unfolds in a series of episodes as well as how the characters respond or change as the plot moves toward a resolution.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "character_analysis"],
  },
  {
    code: "RL.6.4",
    strand: "RL",
    grade: 6,
    number: "4",
    text: "Determine the meaning of words and phrases as they are used in a text, including figurative and connotative meanings; analyze the impact of a specific word choice on meaning and tone.",
    useFor: ["vocabulary"],
  },
  {
    code: "RL.6.5",
    strand: "RL",
    grade: 6,
    number: "5",
    text: "Analyze how a particular sentence, chapter, scene, or stanza fits into the overall structure of a text and contributes to the development of the theme, setting, or plot.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.6.6",
    strand: "RL",
    grade: 6,
    number: "6",
    text: "Explain how an author develops the point of view of the narrator or speaker in a text.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.6.9",
    strand: "RL",
    grade: 6,
    number: "9",
    text: "Compare and contrast texts in different forms or genres (e.g., stories and poems; historical novels and fantasy stories) in terms of their approaches to similar themes and topics.",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 6 ── Reading Informational ────────────────────────────────────────
  {
    code: "RI.6.1",
    strand: "RI",
    grade: 6,
    number: "1",
    text: "Cite textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RI.6.2",
    strand: "RI",
    grade: 6,
    number: "2",
    text: "Determine a central idea of a text and how it is conveyed through particular details; provide a summary of the text distinct from personal opinions or judgments.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RI.6.3",
    strand: "RI",
    grade: 6,
    number: "3",
    text: "Analyze in detail how a key individual, event, or idea is introduced, illustrated, and elaborated in a text (e.g., through examples or anecdotes).",
    useFor: ["think_about_the_story", "reading_between_the_lines"],
  },
  {
    code: "RI.6.4",
    strand: "RI",
    grade: 6,
    number: "4",
    text: "Determine the meaning of words and phrases as they are used in a text, including figurative, connotative, and technical meanings.",
    useFor: ["vocabulary"],
  },
  {
    code: "RI.6.6",
    strand: "RI",
    grade: 6,
    number: "6",
    text: "Determine an author's point of view or purpose in a text and explain how it is conveyed in the text.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RI.6.8",
    strand: "RI",
    grade: 6,
    number: "8",
    text: "Trace and evaluate the argument and specific claims in a text, distinguishing claims that are supported by reasons and evidence from claims that are not.",
    useFor: ["reading_between_the_lines", "dig_deeper"],
  },
  {
    code: "RI.6.9",
    strand: "RI",
    grade: 6,
    number: "9",
    text: "Compare and contrast one author's presentation of events with that of another (e.g., a memoir written by and a biography on the same person).",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 6 ── Writing ───────────────────────────────────────────────────────
  {
    code: "W.6.1",
    strand: "W",
    grade: 6,
    number: "1",
    text: "Write arguments to support claims with clear reasons and relevant evidence.",
    useFor: ["creative_response"],
  },
  {
    code: "W.6.2",
    strand: "W",
    grade: 6,
    number: "2",
    text: "Write informative/explanatory texts to examine a topic and convey ideas, concepts, and information through the selection, organization, and analysis of relevant content.",
    useFor: ["creative_response"],
  },
  {
    code: "W.6.3",
    strand: "W",
    grade: 6,
    number: "3",
    text: "Write narratives to develop real or imagined experiences or events using effective technique, relevant descriptive details, and well-structured event sequences.",
    useFor: ["creative_response"],
  },
  {
    code: "W.6.4",
    strand: "W",
    grade: 6,
    number: "4",
    text: "Produce clear and coherent writing in which the development, organization, and style are appropriate to task, purpose, and audience.",
    useFor: ["creative_response"],
  },
  {
    code: "W.6.5",
    strand: "W",
    grade: 6,
    number: "5",
    text: "With some guidance and support from peers and adults, develop and strengthen writing as needed by planning, revising, editing, rewriting, or trying a new approach.",
    useFor: ["creative_response"],
  },
  {
    code: "W.6.9",
    strand: "W",
    grade: 6,
    number: "9",
    text: "Draw evidence from literary or informational texts to support analysis, reflection, and research.",
    useFor: ["evidence_from_the_story"],
  },
  {
    code: "W.6.9a",
    strand: "W",
    grade: 6,
    number: "9",
    subNumber: "a",
    text: "Apply grade 6 Reading standards to literature (e.g., 'Compare and contrast texts in different forms or genres in terms of their approaches to similar themes and topics').",
    useFor: ["evidence_from_the_story"],
  },
  {
    code: "W.6.10",
    strand: "W",
    grade: 6,
    number: "10",
    text: "Write routinely over extended time frames (time for research, reflection, and revision) and shorter time frames (a single sitting or a day or two) for a range of discipline-specific tasks, purposes, and audiences.",
    useFor: ["creative_response"],
  },

  // ─── GRADE 7 ── Reading Literature ───────────────────────────────────────────
  {
    code: "RL.7.1",
    strand: "RL",
    grade: 7,
    number: "1",
    text: "Cite several pieces of textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RL.7.2",
    strand: "RL",
    grade: 7,
    number: "2",
    text: "Determine a theme or central idea of a text and analyze its development over the course of the text; provide an objective summary of the text.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RL.7.3",
    strand: "RL",
    grade: 7,
    number: "3",
    text: "Analyze how particular elements of a story or drama interact (e.g., how setting shapes the characters or plot).",
    useFor: ["think_about_the_story", "reading_between_the_lines", "character_analysis"],
  },
  {
    code: "RL.7.4",
    strand: "RL",
    grade: 7,
    number: "4",
    text: "Determine the meaning of words and phrases as they are used in a text, including figurative and connotative meanings; analyze the impact of rhymes and other repetitions of sounds (e.g., alliteration) on a specific verse or stanza of a poem or section of a story or drama.",
    useFor: ["vocabulary"],
  },
  {
    code: "RL.7.5",
    strand: "RL",
    grade: 7,
    number: "5",
    text: "Analyze how a drama's or poem's form or structure (e.g., soliloquy, sonnet) contributes to its meaning.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.7.6",
    strand: "RL",
    grade: 7,
    number: "6",
    text: "Analyze how an author develops and contrasts the points of view of different characters or narrators in a text.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.7.9",
    strand: "RL",
    grade: 7,
    number: "9",
    text: "Compare and contrast a fictional portrayal of a time, place, or character and a historical account of the same period as a means of understanding how authors of fiction use or alter history.",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 7 ── Reading Informational ────────────────────────────────────────
  {
    code: "RI.7.1",
    strand: "RI",
    grade: 7,
    number: "1",
    text: "Cite several pieces of textual evidence to support analysis of what the text says explicitly as well as inferences drawn from the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RI.7.2",
    strand: "RI",
    grade: 7,
    number: "2",
    text: "Determine two or more central ideas in a text and analyze their development over the course of the text; provide an objective summary of the text.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RI.7.3",
    strand: "RI",
    grade: 7,
    number: "3",
    text: "Analyze the interactions between individuals, events, and ideas in a text (e.g., how ideas influence individuals or events, or how individuals influence ideas or events).",
    useFor: ["think_about_the_story", "reading_between_the_lines"],
  },
  {
    code: "RI.7.4",
    strand: "RI",
    grade: 7,
    number: "4",
    text: "Determine the meaning of words and phrases as they are used in a text, including figurative, connotative, and technical meanings; analyze the impact of a specific word choice on meaning and tone.",
    useFor: ["vocabulary"],
  },
  {
    code: "RI.7.6",
    strand: "RI",
    grade: 7,
    number: "6",
    text: "Determine an author's point of view or purpose in a text and analyze how the author distinguishes his or her position from others.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RI.7.8",
    strand: "RI",
    grade: 7,
    number: "8",
    text: "Trace and evaluate the argument and specific claims in a text, assessing whether the reasoning is sound and the evidence is relevant and sufficient to support the claims.",
    useFor: ["reading_between_the_lines", "dig_deeper"],
  },
  {
    code: "RI.7.9",
    strand: "RI",
    grade: 7,
    number: "9",
    text: "Analyze how two or more authors writing about the same topic shape their presentations of key information by emphasizing different evidence or advancing different interpretations of facts.",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 7 ── Writing ───────────────────────────────────────────────────────
  {
    code: "W.7.1",
    strand: "W",
    grade: 7,
    number: "1",
    text: "Write arguments to support claims with clear reasons and relevant evidence.",
    useFor: ["creative_response"],
  },
  {
    code: "W.7.2",
    strand: "W",
    grade: 7,
    number: "2",
    text: "Write informative/explanatory texts to examine a topic and convey ideas, concepts, and information through the selection, organization, and analysis of relevant content.",
    useFor: ["creative_response"],
  },
  {
    code: "W.7.3",
    strand: "W",
    grade: 7,
    number: "3",
    text: "Write narratives to develop real or imagined experiences or events using effective technique, relevant descriptive details, and well-structured event sequences.",
    useFor: ["creative_response"],
  },
  {
    code: "W.7.4",
    strand: "W",
    grade: 7,
    number: "4",
    text: "Produce clear and coherent writing in which the development, organization, and style are appropriate to task, purpose, and audience.",
    useFor: ["creative_response"],
  },
  {
    code: "W.7.5",
    strand: "W",
    grade: 7,
    number: "5",
    text: "With some guidance and support from peers and adults, develop and strengthen writing as needed by planning, revising, editing, rewriting, or trying a new approach.",
    useFor: ["creative_response"],
  },
  {
    code: "W.7.9",
    strand: "W",
    grade: 7,
    number: "9",
    text: "Draw evidence from literary or informational texts to support analysis, reflection, and research.",
    useFor: ["evidence_from_the_story"],
  },
  {
    code: "W.7.9a",
    strand: "W",
    grade: 7,
    number: "9",
    subNumber: "a",
    text: "Apply grade 7 Reading standards to literature (e.g., 'Analyze how particular elements of a story or drama interact').",
    useFor: ["evidence_from_the_story"],
  },
  {
    code: "W.7.10",
    strand: "W",
    grade: 7,
    number: "10",
    text: "Write routinely over extended time frames (time for research, reflection, and revision) and shorter time frames (a single sitting or a day or two) for a range of discipline-specific tasks, purposes, and audiences.",
    useFor: ["creative_response"],
  },

  // ─── GRADE 8 ── Reading Literature ───────────────────────────────────────────
  {
    code: "RL.8.1",
    strand: "RL",
    grade: 8,
    number: "1",
    text: "Cite the textual evidence that most strongly supports an analysis of what the text says explicitly as well as inferences drawn from the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RL.8.2",
    strand: "RL",
    grade: 8,
    number: "2",
    text: "Determine a theme or central idea of a text and analyze its development over the course of the text, including its relationship to the characters, setting, and plot; provide an objective summary of the text.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RL.8.3",
    strand: "RL",
    grade: 8,
    number: "3",
    text: "Analyze how particular lines of dialogue or incidents in a story or drama propel the action, reveal aspects of a character, or provoke a decision.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "character_analysis"],
  },
  {
    code: "RL.8.4",
    strand: "RL",
    grade: 8,
    number: "4",
    text: "Determine the meaning of words and phrases as they are used in a text, including figurative and connotative meanings; analyze the impact of specific word choices on meaning and tone, including analogies or allusions to other texts.",
    useFor: ["vocabulary"],
  },
  {
    code: "RL.8.5",
    strand: "RL",
    grade: 8,
    number: "5",
    text: "Compare and contrast the structure of two or more texts and analyze how the differing structure of each text contributes to its meaning and style.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.8.6",
    strand: "RL",
    grade: 8,
    number: "6",
    text: "Analyze how differences in the points of view of the characters and the audience or reader (e.g., created through the use of dramatic irony) create such effects as suspense or humor.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RL.8.9",
    strand: "RL",
    grade: 8,
    number: "9",
    text: "Analyze how a modern work of fiction draws on themes, patterns of events, or character types from myths, traditional stories, or religious works such as the Bible, including describing how the material is rendered new.",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 8 ── Reading Informational ────────────────────────────────────────
  {
    code: "RI.8.1",
    strand: "RI",
    grade: 8,
    number: "1",
    text: "Cite the textual evidence that most strongly supports an analysis of what the text says explicitly as well as inferences drawn from the text.",
    useFor: ["think_about_the_story", "reading_between_the_lines", "multiple_choice"],
  },
  {
    code: "RI.8.2",
    strand: "RI",
    grade: 8,
    number: "2",
    text: "Determine a central idea of a text and analyze its development over the course of the text, including its relationship to supporting ideas; provide an objective summary of the text.",
    useFor: ["dig_deeper", "think_about_the_story"],
  },
  {
    code: "RI.8.3",
    strand: "RI",
    grade: 8,
    number: "3",
    text: "Analyze how a text makes connections among and distinctions between individuals, ideas, or events (e.g., through comparisons, analogies, or categories).",
    useFor: ["think_about_the_story", "reading_between_the_lines"],
  },
  {
    code: "RI.8.4",
    strand: "RI",
    grade: 8,
    number: "4",
    text: "Determine the meaning of words and phrases as they are used in a text, including figurative, connotative, and technical meanings; analyze the impact of specific word choices on meaning and tone.",
    useFor: ["vocabulary"],
  },
  {
    code: "RI.8.6",
    strand: "RI",
    grade: 8,
    number: "6",
    text: "Determine an author's point of view or purpose in a text and analyze how the author acknowledges and responds to conflicting evidence or viewpoints.",
    useFor: ["dig_deeper", "reading_between_the_lines"],
  },
  {
    code: "RI.8.8",
    strand: "RI",
    grade: 8,
    number: "8",
    text: "Delineate and evaluate the argument and specific claims in a text, assessing whether the reasoning is sound and the evidence is relevant and sufficient; recognize when irrelevant evidence is introduced.",
    useFor: ["reading_between_the_lines", "dig_deeper"],
  },
  {
    code: "RI.8.9",
    strand: "RI",
    grade: 8,
    number: "9",
    text: "Analyze a case in which two or more texts provide conflicting information on the same topic and identify where the texts disagree on matters of fact or interpretation.",
    useFor: ["dig_deeper"],
  },
  // ─── GRADE 8 ── Writing ───────────────────────────────────────────────────────
  {
    code: "W.8.1",
    strand: "W",
    grade: 8,
    number: "1",
    text: "Write arguments to support claims with clear reasons and relevant evidence.",
    useFor: ["creative_response"],
  },
  {
    code: "W.8.2",
    strand: "W",
    grade: 8,
    number: "2",
    text: "Write informative/explanatory texts to examine a topic and convey ideas, concepts, and information through the selection, organization, and analysis of relevant content.",
    useFor: ["creative_response"],
  },
  {
    code: "W.8.3",
    strand: "W",
    grade: 8,
    number: "3",
    text: "Write narratives to develop real or imagined experiences or events using effective technique, relevant descriptive details, and well-structured event sequences.",
    useFor: ["creative_response"],
  },
  {
    code: "W.8.4",
    strand: "W",
    grade: 8,
    number: "4",
    text: "Produce clear and coherent writing in which the development, organization, and style are appropriate to task, purpose, and audience.",
    useFor: ["creative_response"],
  },
  {
    code: "W.8.5",
    strand: "W",
    grade: 8,
    number: "5",
    text: "With some guidance and support from peers and adults, develop and strengthen writing as needed by planning, revising, editing, rewriting, or trying a new approach.",
    useFor: ["creative_response"],
  },
  {
    code: "W.8.9",
    strand: "W",
    grade: 8,
    number: "9",
    text: "Draw evidence from literary or informational texts to support analysis, reflection, and research.",
    useFor: ["evidence_from_the_story"],
  },
  {
    code: "W.8.9a",
    strand: "W",
    grade: 8,
    number: "9",
    subNumber: "a",
    text: "Apply grade 8 Reading standards to literature (e.g., 'Analyze how a modern work of fiction draws on themes, patterns of events, or character types from myths, traditional stories, or religious works').",
    useFor: ["evidence_from_the_story"],
  },
  {
    code: "W.8.10",
    strand: "W",
    grade: 8,
    number: "10",
    text: "Write routinely over extended time frames (time for research, reflection, and revision) and shorter time frames (a single sitting or a day or two) for a range of discipline-specific tasks, purposes, and audiences.",
    useFor: ["creative_response"],
  },
];

// ─── Language (L) and Speaking & Listening (SL) — grades 3–8 ───
// Covers L.x.4 (vocabulary strategies), L.x.5 (figurative language / word
// relationships), SL.x.1 (collaborative discussion), and SL.x.3 (evaluating
// speaker reasoning). These map to the Words-to-Know mini-lesson and the
// discussion / common-student-questions blocks in the Teacher Guide.
const L_TEXT_4: Record<GradeLevel, string> = {
  3: "Determine or clarify the meaning of unknown and multiple-meaning word and phrases based on grade 3 reading and content, choosing flexibly from a range of strategies.",
  4: "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 4 reading and content, choosing flexibly from a range of strategies.",
  5: "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 5 reading and content, choosing flexibly from a range of strategies.",
  6: "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 6 reading and content, choosing flexibly from a range of strategies.",
  7: "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 7 reading and content, choosing flexibly from a range of strategies.",
  8: "Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 8 reading and content, choosing flexibly from a range of strategies.",
};

const L_TEXT_5 =
  "Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.";

const SL_TEXT_1: Record<GradeLevel, string> = {
  3: "Engage effectively in a range of collaborative discussions (one-on-one, in groups, and teacher-led) with diverse partners on grade 3 topics and texts, building on others' ideas and expressing their own clearly.",
  4: "Engage effectively in a range of collaborative discussions (one-on-one, in groups, and teacher-led) with diverse partners on grade 4 topics and texts, building on others' ideas and expressing their own clearly.",
  5: "Engage effectively in a range of collaborative discussions (one-on-one, in groups, and teacher-led) with diverse partners on grade 5 topics and texts, building on others' ideas and expressing their own clearly.",
  6: "Engage effectively in a range of collaborative discussions (one-on-one, in groups, and teacher-led) with diverse partners on grade 6 topics, texts, and issues, building on others' ideas and expressing their own clearly.",
  7: "Engage effectively in a range of collaborative discussions (one-on-one, in groups, and teacher-led) with diverse partners on grade 7 topics, texts, and issues, building on others' ideas and expressing their own clearly.",
  8: "Engage effectively in a range of collaborative discussions (one-on-one, in groups, and teacher-led) with diverse partners on grade 8 topics, texts, and issues, building on others' ideas and expressing their own clearly.",
};

const SL_TEXT_3: Record<GradeLevel, string> = {
  3: "Ask and answer questions about information from a speaker, offering appropriate elaboration and detail.",
  4: "Identify the reasons and evidence a speaker provides to support particular points.",
  5: "Summarize the points a speaker makes and explain how each claim is supported by reasons and evidence.",
  6: "Delineate a speaker's argument and specific claims, distinguishing claims that are supported by reasons and evidence from claims that are not.",
  7: "Delineate a speaker's argument and specific claims, evaluating the soundness of the reasoning and the relevance and sufficiency of the evidence.",
  8: "Delineate a speaker's argument and specific claims, evaluating the soundness of the reasoning and relevance and sufficiency of the evidence and identifying when irrelevant evidence is introduced.",
};

for (const grade of [3, 4, 5, 6, 7, 8] as GradeLevel[]) {
  ALL_STANDARDS.push(
    {
      code: `L.${grade}.4`,
      strand: "L",
      grade,
      number: "4",
      text: L_TEXT_4[grade],
      useFor: ["vocabulary", "vocabulary_mini_lesson"],
    },
    {
      code: `L.${grade}.5`,
      strand: "L",
      grade,
      number: "5",
      text: L_TEXT_5,
      useFor: ["vocabulary", "vocabulary_mini_lesson"],
    },
    {
      code: `SL.${grade}.1`,
      strand: "SL",
      grade,
      number: "1",
      text: SL_TEXT_1[grade],
      useFor: ["discussion", "common_student_questions"],
    },
    {
      code: `SL.${grade}.3`,
      strand: "SL",
      grade,
      number: "3",
      text: SL_TEXT_3[grade],
      useFor: ["discussion", "common_student_questions"],
    },
  );
}

export function standardsByGradeAndStrand(
  grade: GradeLevel,
  strand: StandardStrand,
): ELAStandard[] {
  return ALL_STANDARDS.filter((s) => s.grade === grade && s.strand === strand);
}

export { ALL_STANDARDS };
