const GRADE_3_TARGET_WORDS = [
  "ability", "absorb", "accuse", "act", "active", "actual", "adopt", "advantage", "advice", "ambition", "ancient", "approach", "arrange", "arctic", "attitude", "attract", "average", "avoid",
  "bold", "border", "brief", "brilliant",
  "cable", "capture", "certain", "chill", "clever", "climate", "cling", "coast", "confess", "consider", "contain", "continent", "convince", "coward", "crew", "crumple", "custom",
  "decay", "deed", "defend", "delicate", "device", "diagram", "digest", "disease", "distant", "doze", "drift",
  "elegant", "enable", "examine", "explore",
  "fan", "fatal", "fierce", "flutter", "fortunate", "frail",
  "gasp", "glide", "globe", "grace", "gradual", "grasp",
  "habit", "harsh", "imitate", "individual", "intelligent", "intend",
  "journey",
  "launch", "limit", "locate", "loyal",
  "magnificent", "marsh", "method", "misery", "moisture", "mural", "mystify",
  "nation", "nectar", "nursery",
  "observe", "opponent", "opposite", "ordeal", "origin", "outcome",
  "passage", "pastime", "pause", "perform", "plunge", "predator", "predict", "prevent", "primary", "privilege", "process",
  "rare", "rate", "recall", "rely", "remark", "resident", "respect", "responsible", "reverse", "revive", "risk",
  "scatter", "schedule", "sensitive", "signal", "solution", "spoil", "starve", "steer", "struggle", "struggled", "suitable", "survey", "swift", "symbol",
  "talent", "theory", "thrill", "treasure", "triumph",
  "value", "vision", "volunteer",
  "wander", "wisdom", "wit", "woe",
] as const;

const GRADE_4_TARGET_WORDS = [
  "accurate", "address", "afford", "alert", "analyze", "ancestor", "annual", "apparent", "appropriate", "arena", "arrest", "ascend", "assist", "attempt", "attentive", "attractive", "awkward",
  "baggage", "basic", "benefit", "blend", "blossom", "burrow",
  "calculate", "capable", "captivity", "carefree", "century", "chamber", "circular", "coax", "column", "communicate", "competition", "complete", "concentrate", "concern", "conclude", "confuse", "congratulate", "considerable", "content", "contribute", "crafty", "create",
  "demonstrate", "descend", "desire", "destructive", "develop", "disaster", "disclose", "distract", "distress", "dusk",
  "eager", "ease", "entertain", "entire", "entrance", "envy", "essential", "extraordinary",
  "flexible", "focus", "fragile", "frantic", "frequent", "frontier", "furious",
  "generosity",
  "hail", "hardship", "heroic", "host", "humble",
  "impact", "increase", "indicate", "inspire", "instant", "invisible",
  "jagged",
  "lack", "limb", "limp",
  "manufacture", "master", "mature", "meadow", "mistrust", "mock", "modest",
  "noble",
  "orchard", "outstanding",
  "peculiar", "peer", "permit", "plead", "plentiful", "pointless", "portion", "practice", "precious", "prefer", "prepare", "proceed",
  "queasy",
  "recent", "recognize", "reduce", "release", "represent", "request", "resist", "response", "reveal", "routine",
  "severe", "shabby", "shallow", "sole", "source", "sturdy", "surface", "survive",
  "terror", "threat", "tidy", "tour", "tradition", "tragic", "typical",
  "vacant", "valiant", "variety", "vast", "venture",
  "weary",
] as const;

const GRADE_5_TARGET_WORDS = [
  "abolish", "absurd", "abuse", "access", "accomplish", "achievement", "aggressive", "alternate", "altitude", "antagonist", "antonym", "anxious", "apparent", "approximate", "aroma", "assume", "astound", "available", "avalanche",
  "banquet", "beverage", "bland", "blizzard", "budge", "bungle",
  "cautiously", "challenge", "character", "combine", "companion", "crave", "compassion", "compensate", "comply", "compose", "concept", "confident", "convert", "course", "courteous",
  "debate", "decline", "dedicate", "deprive", "detect", "dictate", "document", "duplicate",
  "edible", "endanger", "escalate", "evade", "exasperate", "excavate", "exert", "exhibit", "exult",
  "feeble", "frigid",
  "gigantic", "gorge", "guardian",
  "hazy", "hearty", "homonym",
  "identical", "illuminate", "immense", "impressive", "independent", "industrious", "intense", "intercept",
  "jubilation",
  "kin",
  "luxurious",
  "major", "miniature", "minor", "mischief", "monarch", "moral", "myth",
  "narrator", "navigate", "negative", "nonchalant", "numerous",
  "oasis", "obsolete", "occasion", "overthrow",
  "pardon", "pasture", "pedestrian", "perish", "petrify", "portable", "prefix", "preserve", "protagonist", "provide", "purchase",
] as const;

const GRADE_6_TARGET_WORDS = [
  "abandon", "abundant", "access", "accommodate", "accumulate", "adapt", "adhere", "agony", "allegiance", "ambition", "ample", "anguish", "anticipate", "anxious", "apparel", "appeal", "apprehensive", "arid", "arrogant", "awe",
  "barren", "beacon", "beneficial", "blunder", "boisterous", "boycott", "burden",
  "campaign", "capacity", "capital", "chronological", "civic", "clarity", "collaborate", "collide", "commend", "commentary", "compact", "composure", "concise", "consent", "consequence", "conserve", "conspicuous", "constant", "contaminate", "context", "continuous", "controversy", "convenient", "cope", "cordial", "cultivate", "cumulative",
  "declare", "deluge", "dense", "deplete", "deposit", "designate", "desperate", "deteriorate", "dialogue", "diligent", "diminish", "discretion", "dissent", "dissolve", "distinct", "diversity", "domestic", "dominate", "drastic", "duration", "dwell",
  "eclipse", "economy", "eerie", "effect", "efficient", "elaborate", "eligible", "elude", "encounter", "equivalent", "erupt", "esteem", "evolve", "exaggerate", "excel", "exclude", "expanse", "exploit", "extinct", "extract",
  "factor", "former", "formulate", "formulates", "fuse", "futile",
  "generate", "genre",
  "habitat", "hazardous", "hoax", "hostile",
  "idiom", "ignite", "immense", "improvise", "improvises", "inept", "inevitable", "influence", "ingenious", "innovation", "intimidate",
  "jovial",
  "knack",
  "leeway", "legislation", "leisure", "liberate", "likeness", "linger", "literal", "loathe", "lure",
  "majority", "makeshift", "manipulate", "marvel", "massive", "maximum", "meager", "mere", "migration", "mimic", "minute", "monotonous",
  "negotiate",
  "objective", "obstacle", "omniscient", "onset", "optimist", "originate",
  "painstaking", "paraphrase", "parody", "persecute", "plummet", "possess", "poverty", "precise", "predicament", "predict", "prejudice", "preliminary", "primitive", "priority", "prominent", "propel", "prosecute", "prosper", "provoke", "pursue",
  "quest",
  "recount", "refuge", "reinforce", "reluctant", "remorse", "remote", "resolute", "restrain", "retaliate", "retrieve", "rigorous", "rural",
  "salvage", "sanctuary", "siege", "significant", "solar", "soothe", "stationary", "stifle", "strive", "subordinate", "subsequent", "superior", "supplement", "swarm",
  "tangible", "terminate", "terrain", "trait", "transform", "transport", "treacherous",
  "unanimous", "unique", "unruly", "urban",
  "vacate", "verdict", "verge", "vibrant", "vital", "vow",
] as const;

const GRADE_7_TARGET_WORDS = [
  "abate", "abnormal", "abode", "abrupt", "accelerate", "acclaim", "acknowledge", "acquire", "aspire", "acrid", "addict", "adjacent", "admonish", "affliction", "agitate", "ajar", "akin", "allege", "annihilate", "anonymous", "antagonize", "apathy", "arbitrate", "astute", "authentic", "avert",
  "bellow", "beseech", "bestow", "bewilder", "bigot", "blatant", "bleak", "braggart", "brawl", "browse", "bystander",
  "candid", "canine", "canny", "capricious", "capsize", "casual", "casualty", "catastrophe", "cater", "chorus", "citrus", "clamber", "climax", "compromise", "concur", "confront", "congested", "conjure", "consult", "corrupt", "counterfeit", "covet", "customary",
  "debut", "deceased", "dependent", "despondent", "detach", "devour", "dishearten", "dismal", "dismantle", "distraught", "docile", "downright", "drone", "dumbfound",
  "emblem", "endure", "ensue", "enthrall", "epidemic", "erode", "exuberant",
  "fathom", "feud", "figment", "firebrand", "flabbergast", "flagrant", "flaw", "fruitless",
  "gaudy", "geography", "gratify", "gravity", "grim", "grimy", "grueling", "gruesome",
  "haggle", "headlong", "hilarious", "homage", "homicide", "hospitable", "hurtle", "hybrid",
  "illiterate", "impede", "implore", "incident", "incredulous", "infamous", "infuriate", "insinuate", "intensified", "inundate", "irate",
  "lavish", "legacy", "legitimate", "lethal", "loath", "lurk",
  "magnetic", "mirth", "quench", "magnitude", "maternal", "maul", "melancholy", "mellow", "momentum", "mortify", "mull", "murky",
  "narrative", "negligent", "nimble", "nomadic", "noteworthy", "notify", "notorious", "nurture",
  "obnoxious", "oration", "orthodox", "overwhelm",
  "pamper", "patronize", "peevish", "pelt", "pending", "perceived", "perjury", "permanent", "persist", "perturb", "pique", "pluck", "poised", "ponder", "potential", "predatory", "presume", "preview", "prior", "prowess",
  "radiant", "random", "rant", "recede", "reprimand", "resume", "retort", "robust", "rupture",
  "saga", "sequel", "sham", "shirk", "simultaneously", "snare", "species", "status", "stodgy", "substantial", "subtle", "sullen", "supervise",
  "tamper", "throb", "toxic", "tragedy", "trickle", "trivial",
  "uncertainty", "unscathed", "upright", "urgent", "utmost",
  "vengeance", "vicious", "vindictive", "vista", "vocation", "void",
  "wary", "whim", "wince", "wrath",
  "yearn",
] as const;

const GRADE_8_TARGET_WORDS = [
  "abet", "accord", "adept", "advocate", "agile", "allot", "aloof", "amiss", "analogy", "anarchy", "antics", "apprehend", "ardent", "articulate", "assail", "assimilate", "atrocity", "attribute", "audacious", "augment", "authority", "avail", "avid", "awry",
  "balmy", "banter", "barter", "benign", "bizarre", "blase", "bonanza", "bountiful",
  "cache", "capacious", "caption", "chastise", "citadel", "cite", "clad", "clarify", "commemorate", "component", "concept", "confiscate", "connoisseur", "conscientious", "conservative", "contagious", "conventional", "convey", "crucial", "crusade", "culminate",
  "deceptive", "decipher", "decree", "deface", "defect", "deplore", "deploy", "desist", "desolate", "deter", "dialect", "dire", "discern", "disdain", "disgruntled", "dispatch", "disposition", "doctrine", "dub", "durable",
  "eccentric", "elite", "embargo", "embark", "encroach", "endeavor", "enhance", "enigma", "epoch", "era", "eventful", "evolve", "exceptional", "excerpt", "excruciating", "exemplify", "exotic",
  "facilitate", "fallacy", "fastidious", "feasible", "fend", "ferret", "flair", "flustered", "foreboding", "forfeit", "formidable", "fortify", "foster",
  "gaunt", "gingerly", "glut", "grapple", "grope", "gullible",
  "haggard", "haven", "heritage", "hindrance", "hover", "humane",
  "imperative", "inaugurate", "incense", "indifferent", "infinite", "instill", "institute", "intervene", "intricate", "inventive", "inventory", "irascible",
  "jurisdiction",
  "languish", "legendary", "liberal", "loll", "lucrative", "luminous",
  "memoir", "mercenary", "mien", "millennium", "minimize", "modify", "muse", "muster",
  "onslaught", "ornate", "ovation", "overt",
  "pang", "panorama", "perspective", "phenomenon", "pioneer", "pithy", "pivotal", "plausible", "plunder", "porous", "preposterous", "principal", "prodigy", "proficient", "profound", "pseudonym", "pungent",
  "rankle", "rational", "rebuke", "reception", "recourse", "recur", "renounce", "renown", "revenue", "rubble", "rue",
  "sage", "sedative", "serene", "servile", "shackle", "sleek", "spontaneous", "sporadic", "stamina", "stance", "staple", "stint", "strident", "sublime", "subside", "succumb", "surpass", "susceptible", "swelter",
  "tedious", "teem", "theme", "tirade", "tract", "transition", "trepidation", "turbulent", "tycoon",
  "ultimate", "ungainly",
  "vice", "versa", "vice versa", "vie", "vilify", "voracious",
  "wage", "wrangle",
] as const;

const TARGETS_BY_GRADE: Record<number, Set<string>> = {
  3: new Set(GRADE_3_TARGET_WORDS),
  4: new Set(GRADE_4_TARGET_WORDS),
  5: new Set(GRADE_5_TARGET_WORDS),
  6: new Set(GRADE_6_TARGET_WORDS),
  7: new Set(GRADE_7_TARGET_WORDS),
  8: new Set(GRADE_8_TARGET_WORDS),
};

export function getGradeVocabularyTargets(gradeLevel: number): Set<string> {
  return TARGETS_BY_GRADE[gradeLevel] ?? new Set<string>();
}
