// Grade-banded target vocabulary pools (grades 3-8). Ported byte-for-byte
// from workbook_generator/vocab_selector.py's GRADE_VOCAB dict so selection
// behavior is unchanged after the refactor. Storage is lowercase because the
// selector normalizes both sides of the lookup with `normalizeToken`, which
// lowercases all candidates.

const GRADE_3: string[] = [
  "ability", "absorb", "accuse", "act", "active", "actual", "adopt", "advantage",
  "advice", "ambition", "ancient", "approach", "arrange", "arctic", "attitude", "attract",
  "average", "avoid", "bold", "border", "brief", "brilliant", "cable", "capture",
  "certain", "chill", "clever", "climate", "cling", "coast", "confess", "consider",
  "contain", "continent", "convince", "coward", "crew", "crumple", "custom", "decay",
  "deed", "defend", "delicate", "device", "diagram", "digest", "disease", "distant",
  "doze", "drift", "elegant", "enable", "examine", "explore", "fan", "fatal",
  "fierce", "flutter", "fortunate", "frail", "gasp", "glide", "globe", "grace",
  "gradual", "grasp", "habit", "harsh", "imitate", "individual", "intelligent", "intend",
  "journey", "launch", "limit", "locate", "loyal", "magnificent", "marsh", "method",
  "misery", "moisture", "mural", "mystify", "nation", "nectar", "nursery", "observe",
  "opponent", "opposite", "ordeal", "origin", "outcome", "passage", "pastime", "pause",
  "perform", "plunge", "predator", "predict", "prevent", "primary", "privilege", "process",
  "rare", "rate", "recall", "rely", "remark", "resident", "respect", "responsible",
  "reverse", "revive", "risk", "scatter", "schedule", "sensitive", "signal", "solution",
  "spoil", "starve", "steer", "struggled", "suitable", "survey", "swift", "symbol",
  "talent", "theory", "thrill", "treasure", "triumph", "value", "vision", "volunteer",
  "wander", "wisdom", "wit", "woe",
];

const GRADE_4: string[] = [
  "accurate", "address", "afford", "alert", "analyze", "ancestor", "annual", "apparent",
  "appropriate", "arena", "arrest", "ascend", "assist", "attempt", "attentive", "attractive",
  "awkward", "baggage", "basic", "benefit", "blend", "blossom", "burrow", "calculate",
  "capable", "captivity", "carefree", "century", "chamber", "circular", "coax", "column",
  "communicate", "competition", "complete", "concentrate", "concern", "conclude", "confuse", "congratulate",
  "considerable", "content", "contribute", "crafty", "create", "demonstrate", "descend", "desire",
  "destructive", "develop", "disaster", "disclose", "distract", "distress", "dusk", "eager",
  "ease", "entertain", "entire", "entrance", "envy", "essential", "extraordinary", "flexible",
  "focus", "fragile", "frantic", "frequent", "frontier", "furious", "generosity", "hail",
  "hardship", "heroic", "host", "humble", "impact", "increase", "indicate", "inspire",
  "instant", "invisible", "jagged", "lack", "limb", "limp", "manufacture", "master",
  "mature", "meadow", "mistrust", "mock", "modest", "noble", "orchard", "outstanding",
  "peculiar", "peer", "permit", "plead", "plentiful", "pointless", "portion", "practice",
  "precious", "prefer", "prepare", "proceed", "queasy", "recent", "recognize", "reduce",
  "release", "represent", "request", "resist", "response", "reveal", "routine", "severe",
  "shabby", "shallow", "sole", "source", "sturdy", "surface", "survive", "terror",
  "threat", "tidy", "tour", "tradition", "tragic", "typical", "vacant", "valiant",
  "variety", "vast", "venture", "weary",
];

const GRADE_5: string[] = [
  "abolish", "absurd", "abuse", "access", "accomplish", "achievement", "aggressive", "alternate",
  "altitude", "antagonist", "antonym", "anxious", "apparent", "approximate", "aroma", "assume",
  "astound", "available", "avalanche", "banquet", "beverage", "bland", "blizzard", "budge",
  "bungle", "cautiously", "challenge", "character", "combine", "companion", "crave", "compassion",
  "compensate", "comply", "compose", "concept", "confident", "convert", "course", "courteous",
  "debate", "decline", "dedicate", "deprive", "detect", "dictate", "document", "duplicate",
  "edible", "endanger", "escalate", "evade", "exasperate", "excavate", "exert", "exhibit",
  "exult", "feeble", "frigid", "gigantic", "gorge", "guardian", "hazy", "hearty",
  "homonym", "identical", "illuminate", "immense", "impressive", "independent", "industrious", "intense",
  "intercept", "jubilation", "kin", "luxurious", "major", "miniature", "minor", "mischief",
  "monarch", "moral", "myth", "narrator", "navigate", "negative", "nonchalant", "numerous",
  "oasis", "obsolete", "occasion", "overthrow", "pardon", "pasture", "pedestrian", "perish",
  "petrify", "portable", "prefix", "preserve", "protagonist", "provide", "purchase", "realistic",
  "reassure", "reign", "reliable", "require", "resemble", "retain", "retire", "revert",
  "route", "saunter", "seldom", "senseless", "sever", "slither", "sluggish", "soar",
  "solitary", "solo", "sparse", "spurt", "strategy", "suffix", "suffocate", "summit",
  "suspend", "synonym", "talon", "taunt", "thrifty", "translate", "tropical", "visible",
  "visual", "vivid", "wilderness", "withdraw",
];

const GRADE_6: string[] = [
  "abate", "abnormal", "abode", "abrupt", "accelerate", "acclaim", "acknowledge", "acquire",
  "aspire", "acrid", "addict", "adjacent", "admonish", "affliction", "agitate", "ajar",
  "akin", "allege", "annihilate", "anonymous", "antagonize", "apathy", "arbitrate", "astute",
  "authentic", "avert", "bellow", "beseech", "bestow", "bewilder", "bigot", "blatant",
  "bleak", "braggart", "brawl", "browse", "bystander", "candid", "canine", "canny",
  "capricious", "capsize", "casual", "casualty", "catastrophe", "cater", "chorus", "citrus",
  "clamber", "climax", "compromise", "concur", "confront", "congested", "conjure", "consult",
  "corrupt", "counterfeit", "covet", "customary", "debut", "deceased", "dependent", "despondent",
  "detach", "devour", "dishearten", "dismal", "dismantle", "distraught", "docile", "downright",
  "drone", "dumbfound", "emblem", "endure", "ensue", "enthrall", "epidemic", "erode",
  "exuberant", "fathom", "feud", "figment", "firebrand", "flabbergast", "flagrant", "flaw",
  "fruitless", "gaudy", "geography", "gratify", "gravity", "grim", "grimy", "grueling",
  "gruesome", "haggle", "headlong", "hilarious", "homage", "homicide", "hospitable", "hurtle",
  "hybrid", "illiterate", "impede", "implore", "incident", "incredulous", "infamous", "infuriate",
  "insinuate", "intensified", "inundate", "irate", "lavish", "legacy", "legitimate", "lethal",
  "loath", "lurk", "magnetic", "mirth", "quench", "magnitude", "maternal", "maul",
  "melancholy", "mellow", "momentum", "mortify", "mull", "murky", "narrative", "negligent",
  "nimble", "nomadic", "noteworthy", "notify", "notorious", "nurture", "obnoxious", "oration",
  "orthodox", "overwhelm", "pamper", "patronize", "peevish", "pelt", "pending", "perceived",
  "perjury", "permanent", "persist", "perturb", "pique", "pluck", "poised", "ponder",
  "potential", "predatory", "presume", "preview", "prior", "prowess", "radiant", "random",
  "rant", "recede", "reprimand", "resume", "retort", "robust", "rupture", "saga",
  "sequel", "sham", "shirk", "simultaneously", "snare", "species", "status", "stodgy",
  "substantial", "subtle", "sullen", "supervise", "tamper", "throb", "toxic", "tragedy",
  "trickle", "trivial", "uncertainty", "unscathed", "upright", "urgent", "utmost", "vengeance",
  "vicious", "vindictive", "vista", "vocation", "void", "wary", "whim", "wince",
  "wrath", "yearn",
];

const GRADE_7_AND_8: string[] = [
  "abet", "accord", "adept", "advocate", "agile", "allot", "aloof", "amiss",
  "analogy", "anarchy", "antics", "apprehend", "ardent", "articulate", "assail", "assimilate",
  "atrocity", "attribute", "audacious", "augment", "authority", "avail", "avid", "awry",
  "balmy", "banter", "barter", "benign", "bizarre", "blasé", "bonanza", "bountiful",
  "cache", "capacious", "caption", "chastise", "citadel", "cite", "clad", "clarify",
  "commemorate", "component", "concept", "confiscate", "connoisseur", "conscientious", "conservative", "contagious",
  "conventional", "convey", "crucial", "crusade", "culminate", "deceptive", "decipher", "decree",
  "deface", "defect", "deplore", "deploy", "desist", "desolate", "deter", "dialect",
  "dire", "discern", "disdain", "disgruntled", "dispatch", "disposition", "doctrine", "dub",
  "durable", "eccentric", "elite", "embargo", "embark", "encroach", "endeavor", "enhance",
  "enigma", "epoch", "era", "eventful", "evolve", "exceptional", "excerpt", "excruciating",
  "exemplify", "exotic", "facilitate", "fallacy", "fastidious", "feasible", "fend", "ferret",
  "flair", "flustered", "foreboding", "forfeit", "formidable", "fortify", "foster", "gaunt",
  "gingerly", "glut", "grapple", "grope", "gullible", "haggard", "haven", "heritage",
  "hindrance", "hover", "humane", "imperative", "inaugurate", "incense", "indifferent", "infinite",
  "instill", "institute", "intervene", "intricate", "inventive", "inventory", "irascible", "jurisdiction",
  "languish", "legendary", "liberal", "loll", "lucrative", "luminous", "memoir", "mercenary",
  "mien", "millennium", "minimize", "modify", "muse", "muster", "onslaught", "ornate",
  "ovation", "overt", "pang", "panorama", "perspective", "phenomenon", "pioneer", "pithy",
  "pivotal", "plausible", "plunder", "porous", "preposterous", "principal", "prodigy", "proficient",
  "profound", "pseudonym", "pungent", "rankle", "rational", "rebuke", "reception", "recourse",
  "recur", "renounce", "renown", "revenue", "rubble", "rue", "sage", "sedative",
  "serene", "servile", "shackle", "sleek", "spontaneous", "sporadic", "stamina", "stance",
  "staple", "stint", "strident", "sublime", "subside", "succumb", "surpass", "susceptible",
  "swelter", "tedious", "teem", "theme", "tirade", "tract", "transition", "trepidation",
  "turbulent", "tycoon", "ultimate", "ungainly", "vice versa", "vie", "vilify", "voracious",
  "wage", "wrangle",
];

export const GRADE_VOCAB: Record<number, string[]> = {
  3: GRADE_3,
  4: GRADE_4,
  5: GRADE_5,
  6: GRADE_6,
  7: GRADE_7_AND_8,
  8: GRADE_7_AND_8,
};
